# CHANGEME: Set these variable to your liking
title: HA Assist Mic Satellite
description: The HA Assist Mic Satellite is a compact, ESPHome-based microphone solution designed for seamless integration with Home Assistant.
theme: jekyll-theme-slate