# CHANGEME: Set these variable to your liking
title: Voice Assistant Mic Satellite V1
description: The Voice Assistant Mic Satellite is a compact, ESPHome-based microphone solution designed for seamless integration with Home Assistant.
theme: jekyll-theme-slate