name: Build and Publish Firmware

on: 
  workflow_dispatch:

jobs:
  build:
    uses: MrWyss/ha-assist-mic-satellite/.github/workflows/forked_publish.yml@main
    with:
      files: code/esphome/va-mic-sat-atoms3.yaml
      name: Voice Assistant Mic Satellite