name: CI

on:
  pull_request:
    paths:
      - 'code/esphome/va-mic-sat-atoms3.yaml'

jobs:
  ci:
    name: Building ${{ matrix.file }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        file:
          - code/esphome/va-mic-sat-atoms3.yaml
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4.1.7
      - name: Build ESPHome firmware to verify configuration
        uses: esphome/build-action@v3.2.0
        with:
          yaml_file: ${{ matrix.file }}