name: Build and publish on dispatch
on:
  workflow_dispatch:
    inputs:
      summary:
        description: 'Release summary'
        required: true
        type: string
      version:
        description: 'Release version'
        required: true
        type: string

jobs:
  build:
    uses: ./.github/workflows/build_and_publish.yml
    with:
      files: code/esphome/va-mic-sat-atoms3.yaml
      name: Voice Assistant Mic Satellite
      esphome_version: "latest"
      summary: ${{ inputs.summary }}
      version: ${{ inputs.version }}


