name: Build and Publish ESPHome firmware and website

on:
  push:
    branches: ['main']
    paths: ['code/esphome/**.yaml']

jobs:
  build:
    uses: esphome/workflows/.github/workflows/publish.yml@main
    with:
      files: code/esphome/va-mic-sat-atoms3.yaml
      name: Voice Assistant Mic Satellite
