name: Update Manifest on Release

on:
  release:
    types: [published]

jobs:
  update-manifest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: gh-pages

      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Update manifest file
        run: |
          manifest_file="manifest.json"
          version="${{ github.event.release.tag_name }}"
          summary="${{ github.event.release.body }}"

          jq --arg version "$version" --arg summary "$summary" '
            .version = $version |
            .builds[0].ota.summary = $summary
          ' "$manifest_file" > tmp.$$.json && mv tmp.$$.json "$manifest_file"

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add manifest.json
          git commit -m "Update manifest for release ${{ github.event.release.tag_name }}"
          git push origin gh-pages